name: Publish a new release

on: push

permissions:
  id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
  checks: write
  statuses: write
  contents: write  # IMPORTANT: mandatory for making GitHub Releases

# .github/workflows/ci-cd.yml
jobs:
  build:
      name: Build distribution 📦
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name:  Update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build setuptools setuptools_scm wheel wheel twine
          --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build --wheel --sdist
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
  testpypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/wiseagents/

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    # retrieve your distributions here
    - name: Publish package distributions to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true
    - name: Sign the dists with Sigstore
      uses: sigstore/gh-action-sigstore-python@v2.1.1
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release create
        '${{ github.ref_name }}_008'
        --repo '${{ github.repository }}'
        --notes ""
    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      # Upload to GitHub Release using the `gh` CLI.
      # `dist/` contains the built packages, and the
      # sigstore-produced signatures and certificates.
      run: >-
        gh release upload
        '${{ github.ref_name }}_008' dist/**
        --repo '${{ github.repository }}'